---
name: Github Actions Matrix
on:
  workflow_dispatch:
jobs:
  read_config:
    runs-on: ubuntu-latest
    outputs: 
      lambda: ${{steps.get-lambdas-name.outputs.matrix}}
    steps:
      - name: Just ls
        run: ls

  #     - name: Get configs var
  #       id: get-lambdas-name
  #       run: |
  #         ls
  #         JSON=$(cat configuration.json)
  #         echo "matrix=$JSON" >> $GITHUB_OUTPUT
  # deploy:
  #   needs: [read_config]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix: ${{fromJson(needs.get-lambdas-name.outputs.matrix)}}

  #   steps:
  #     # - name: Checkout repository
  #     #   uses: actions/checkout@v2

  #     - name: Display Matrix Values
  #       run: |
  #         echo "Deploying lambda"