---
name: Github Actions Matrix
on:
  workflow_dispatch:
jobs:
  read_config:
    runs-on: ubuntu-latest
    steps:
      - name: Print configs var
        run: echo "hello"
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [lambda1,lambda2,lambda3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Matrix Values
        run: |
          echo "Deploying lambda: ${{ matrix.os }}"